/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CustomGallery {
        "arrowsPosition": string;
        "arrowsShow": boolean;
        "autoscroll": boolean;
        "autoscrollDelaySeconds": number;
        "caption": boolean;
        "clickableImg": boolean;
        "grid": boolean;
        "gridAutoheight": boolean;
        "imgFit": string;
        "infiniteScroll": boolean;
        "keydownscroll": boolean;
    }
}
declare global {
    interface HTMLCustomGalleryElement extends Components.CustomGallery, HTMLStencilElement {
    }
    var HTMLCustomGalleryElement: {
        prototype: HTMLCustomGalleryElement;
        new (): HTMLCustomGalleryElement;
    };
    interface HTMLElementTagNameMap {
        "custom-gallery": HTMLCustomGalleryElement;
    }
}
declare namespace LocalJSX {
    interface CustomGallery {
        "arrowsPosition"?: string;
        "arrowsShow"?: boolean;
        "autoscroll"?: boolean;
        "autoscrollDelaySeconds"?: number;
        "caption"?: boolean;
        "clickableImg"?: boolean;
        "grid"?: boolean;
        "gridAutoheight"?: boolean;
        "imgFit"?: string;
        "infiniteScroll"?: boolean;
        "keydownscroll"?: boolean;
    }
    interface IntrinsicElements {
        "custom-gallery": CustomGallery;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "custom-gallery": LocalJSX.CustomGallery & JSXBase.HTMLAttributes<HTMLCustomGalleryElement>;
        }
    }
}
